/**
 * Regenerates the Simple Icons logo files in public/logos/.
 *
 * Only the Simple Icons marks are generated. Bazzite and Ubuntu Studio come from
 * their own projects and are committed as downloaded — Bazzite's press kit
 * forbids modifying its logo, so it must stay exactly as published.
 *
 * Files are written EXACTLY as Simple Icons publishes them. Nothing is recoloured
 * on disk: the brand colour is recorded in distros.json as `logoColor` and applied
 * at render time instead. That keeps every file a verbatim redistribution, which
 * is what several of the upstream licences and brand guidelines actually require —
 * Fedora permits inclusion in icon collections only "unmodified from the logo
 * image except in size and/or file format", and Debian (CC BY-SA) and MX Linux
 * (GPL) are far simpler to comply with when nothing is derived from them.
 *
 * Run with: npm run logos
 * Provenance and licensing live in public/logos/LOGOS.md.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import * as simpleIcons from "simple-icons";

/** distro id -> Simple Icons title. */
const MARKS = {
  mint: "Linux Mint",
  ubuntu: "Ubuntu",
  // Ubuntu Server is Ubuntu; Leap and Tumbleweed are both openSUSE.
  "ubuntu-server": "Ubuntu",
  kubuntu: "Kubuntu",
  lubuntu: "Lubuntu",
  zorin: "Zorin",
  popos: "Pop!_OS",
  debian: "Debian",
  fedora: "Fedora",
  "opensuse-leap": "openSUSE",
  "opensuse-tumbleweed": "openSUSE",
  mx: "MX Linux",
  manjaro: "Manjaro",
  endeavouros: "EndeavourOS",
  cachyos: "CachyOS",
  nobara: "Nobara Linux",
  omarchy: "Omarchy",
  "fedora-asahi": "Asahi Linux",
};

const byTitle = new Map(
  Object.values(simpleIcons).filter((i) => i?.title).map((i) => [i.title, i]),
);

const distrosPath = "src/data/distros.json";
const distros = JSON.parse(readFileSync(distrosPath, "utf8"));
const byId = new Map(distros.map((d) => [d.id, d]));

let written = 0;
for (const [id, title] of Object.entries(MARKS)) {
  const icon = byTitle.get(title);
  if (!icon) throw new Error(`simple-icons no longer provides "${title}" (for ${id})`);

  writeFileSync(`public/logos/${id}.svg`, icon.svg + "\n");

  // The brand colour lives in the data, not in the file.
  const distro = byId.get(id);
  if (!distro) throw new Error(`no distro "${id}" in ${distrosPath}`);
  distro.logoColor = `#${icon.hex}`;
  written++;
}

writeFileSync(distrosPath, JSON.stringify(distros, null, 2) + "\n");

// Inline every mark into the bundle. Loading them as external URLs meant the
// page depended on the host serving .svg with the right Content-Type, on
// relative URLs resolving the way they do locally, and on CSS masks and inline
// style attributes surviving whatever a shared host puts in front of the site.
// A string in the bundle depends on none of that.
const markup = {};
for (const file of readdirSync("public/logos").filter((f) => f.endsWith(".svg")).sort()) {
  markup[file.replace(/\.svg$/, "")] = readFileSync(`public/logos/${file}`, "utf8").trim();
}
const ts = `// GENERATED by scripts/generate-logos.mjs — do not edit by hand.
//
// Verbatim copies of the files in public/logos/, inlined so the page never has
// to fetch them.
//
// THIRD-PARTY CONTENT. Unlike the rest of this repository, the strings below are
// NOT covered by the project's MIT licence. They are distribution logos owned by
// their respective projects, aggregated here under their own terms — among them
// CC BY-SA 3.0 (Debian), GPL-3.0-only (MX Linux), Apache-2.0 (Bazzite) and Red
// Hat's brand guidelines (Fedora). The names and marks are trademarks; no
// licence here extends to any trademark.
//
// Provenance and per-file licences: public/logos/LOGOS.md — see also LICENSE.

export const LOGO_MARKUP: Record<string, string> = ${JSON.stringify(markup, null, 2)};
`;
writeFileSync("src/data/logos.ts", ts);

console.log(`wrote ${written} verbatim logos; synced logoColor; inlined ${Object.keys(markup).length} marks`);
